baseURL = "https://dribo.github.io/DTU-02467_ProjectB/"
title = "Slightly Changed Project Title"
description = "This is a project description"
relativeURLs = true
theme = "theme"
[params]
    authors = ["Magnus A. Nielsen", "Philip J. F. Helsted"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/dribo/DTU-02467_ProjectB"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

