baseURL = "https://dribo.github.io/DTU-02467_ProjectB/"
title = "The structure of the Cold War on Wikipedia"
description = "This is a new project description"
relativeURLs = true
theme = "theme"
[params]
    authors = ["Magnus A. Nielsen", "Philip J. F. Helsted"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/dribo/DTU-02467_ProjectB"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text Analysis"
        link = "/text-analysis"
    [[params.nav]]
        label = "Conclusion"
        link = "/conclusion"

